'use client'

import { useState, useEffect } from 'react'
import { useVariables } from './useVariables'

// We expect these to be generated by wasm-pack build --target web
// and placed in /public/wasm/
let wasmModule: any = null
let loadingPromise: Promise<void> | null = null

export function useLogicBot() {
  const [isLoaded, setIsLoaded] = useState(false)
  const [engine, setEngine] = useState<any>(null)
  const [error, setError] = useState<string | null>(null)
  const { variables } = useVariables()

  useEffect(() => {
    async function loadWasm() {
      if (wasmModule) {
        setIsLoaded(true)
        return
      }

      if (loadingPromise) {
        await loadingPromise
        setIsLoaded(true)
        return
      }

      loadingPromise = (async () => {
        try {
          // Use webpackIgnore to prevent the bundler from trying to resolve the WASM dependency
          const wasm = await import(/* webpackIgnore: true */ '/wasm/logic_engine.js' as any)
          
          // Initialize with the explicit public URL to the binary
          // Note: Newer versions expect an object for the initialization
          await wasm.default({ module_or_path: '/wasm/logic_engine_bg.wasm' })
          
          wasmModule = wasm
          setIsLoaded(true)
          setError(null)
        } catch (err: any) {
          const msg = `Logic Bot failed to load: ${err.message || 'Wasm module not found'}`
          console.error(msg, err)
          setError(msg)
          setIsLoaded(false)
          loadingPromise = null // Allow retry
        }
      })()

      await loadingPromise
    }

    loadWasm()
  }, [])

  const createEngine = (initialState: Record<string, any> = {}) => {
    if (!isLoaded || !wasmModule) {
      setError('Cannot create: Logic Bot not loaded')
      return null
    }

    try {
      // Map frontend variables to the format expected by the WASM LogicEngine
      // specifically mapping 'type' to 'value_type'
      const engineVariables = variables.map(v => ({
        ...v,
        value_type: v.type
      }))

      const newEngine = new wasmModule.LogicEngine(
        engineVariables,
        { values: initialState }
      )
      setEngine(newEngine)
      setError(null)
      return newEngine
    } catch (err: any) {
      const msg = `Engine initialization failed: ${err.message}`
      console.error(msg, err)
      setError(msg)
      return null
    }
  }

  const evaluateExpression = (expression: string) => {
    if (!engine) return null
    try {
      return engine.evaluate(expression)
    } catch (err: any) {
      console.error('Evaluation failed:', err)
      return null
    }
  }

  return {
    isLoaded,
    error,
    engine,
    createEngine,
    evaluateExpression,
  }
}
