'use client'

import { useState, useEffect } from 'react'
import { useVariables } from './useVariables'

// We expect these to be generated by wasm-pack build --target web
// and placed in /public/wasm/
let wasmModule: any = null

export function useLogicBot() {
  const [isLoaded, setIsLoaded] = useState(false)
  const [engine, setEngine] = useState<any>(null)
  const [error, setError] = useState<string | null>(null)
  const { variables } = useVariables()

  useEffect(() => {
    async function loadWasm() {
      if (wasmModule) {
        setIsLoaded(true)
        return
      }

      try {
        // Load the module using Next.js/Webpack's native WASM support
        const module = await import('@/lib/wasm/logic_engine')
        wasmModule = module
        setIsLoaded(true)
        setError(null)
      } catch (err: any) {
        const msg = `Logic Bot failed to load: ${err.message || 'Wasm module not found'}`
        console.error(msg, err)
        setError(msg)
        setIsLoaded(false)
      }
    }

    loadWasm()
  }, [])

  const createEngine = (initialState: Record<string, any> = {}) => {
    if (!isLoaded || !wasmModule) {
      setError('Cannot create: Logic Bot not loaded')
      return null
    }

    try {
      const newEngine = new wasmModule.LogicEngine(
        variables,
        { values: initialState }
      )
      setEngine(newEngine)
      setError(null)
      return newEngine
    } catch (err: any) {
      const msg = `Engine initialization failed: ${err.message}`
      console.error(msg, err)
      setError(msg)
      return null
    }
  }

  const evaluateExpression = (expression: string) => {
    if (!engine) return null
    try {
      return engine.evaluate(expression)
    } catch (err: any) {
      console.error('Evaluation failed:', err)
      return null
    }
  }

  return {
    isLoaded,
    error,
    engine,
    createEngine,
    evaluateExpression,
  }
}
