import { NextResponse } from 'next/server'

// Use edge runtime for faster responses if deployed, otherwise node is fine
export const runtime = 'edge'

export async function POST(req: Request) {
  try {
    const { prompt, currentState } = await req.json()

    // Ensure we have a prompt
    if (!prompt) {
      return NextResponse.json({ error: 'Missing prompt' }, { status: 400 })
    }

    const OPENAI_API_KEY = process.env.OPENAI_API_KEY

    // If an API key is provided, we do a real LLM call
    if (OPENAI_API_KEY) {
      const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${OPENAI_API_KEY}`
        },
        body: JSON.stringify({
          model: 'gpt-4-turbo-preview', // or gpt-4o
          messages: [
            {
              role: 'system',
              content: `You are the STEM System Architect. You generate deterministic system blueprints in STEM-script.
              
CURRENT SYSTEM STATE:
${currentState}

INSTRUCTIONS:
1. Analyze the user's intent based on the CURRENT SYSTEM STATE.
2. Generate ONLY valid STEM-script to mutate the state. No markdown formatting, just the raw text script.
3. STEM-script syntax:
   screen "Name" {
      description: "..."
      constraint: "..." !! "Fallback Screen"
   }
   "Screen A" -> "Screen B"
`
            },
            {
              role: 'user',
              content: prompt
            }
          ],
          temperature: 0.2
        })
      })

      if (!response.ok) {
        throw new Error('OpenAI API request failed')
      }

      const data = await response.json()
      const script = data.choices[0].message.content.trim()

      return NextResponse.json({
        content: "I've analyzed your system state and generated the following architectural updates based on your request.",
        script
      })
    }

    // ==========================================
    // FALLBACK MOCK (If no API key is present)
    // ==========================================
    console.warn("No OPENAI_API_KEY found. Using local simulated responses.")
    await new Promise(resolve => setTimeout(resolve, 1500))

    let script = ''
    let content = ''
    const lPrompt = prompt.toLowerCase()

    if (lPrompt.includes('saas') || lPrompt.includes('login') || lPrompt.includes('auth')) {
      content = "I've architected a standard high-security authentication and dashboard flow based on your current state."
      script = `
screen "Landing Page" {
    description: "Public system entry point"
}

screen "Auth Portal" {
    description: "Unified Login/Signup interface"
}

screen "Dashboard" {
    description: "Primary workspace"
    constraint: "user.auth == true" !! "Auth Portal"
}

# Flows
"Landing Page" -> "Auth Portal"
"Auth Portal" -> "Dashboard"
      `.trim()
    } else {
      content = "I've processed your architectural intent. Without an OpenAI API key, I am providing a default structural component."
      script = `
screen "New Interface" {
    description: "Generated by STEM Architect"
}

# Flows
"New Interface" -> "Settings"
      `.trim()
    }

    return NextResponse.json({ content, script })

  } catch (error: any) {
    console.error('API /architect error:', error)
    return NextResponse.json({ error: error.message || 'Failed to process request' }, { status: 500 })
  }
}
